variables:
  MAVEN_CLI_OPTS: "clean"

build:
  stage: build
  script:
    - mvn -Denv=test $MAVEN_CLI_OPTS compile
  tags:
    - dalfcs_gitlab_docker_ci

test:
  stage: test
  script:
    - mvn -Denv=test verify
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - dalfcs_gitlab_docker_ci

deploy:
  stage: deploy
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop
  tags:
    - dalfcs_gitlab_docker_ci