variables:
  MAVEN_CLI_OPTS: "clean"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  tags:
    - ugrad

test:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

