variables:
  MAVEN_CLI_OPTS: "clean"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile -Ptest -DprofileIdEnabled=true
  tags:
    - dalfcs_docker_kvm
  only:
    - develop

test:
  stage: test
  script:
    - mvn verify -Ptest -DprofileIdEnabled=true
  artifacts:
    when: always
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - dalfcs_docker_kvm

deploy:
  stage: deploy
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - develop
  tags:
    - dalfcs_docker_kvm